### ISSUE TITLE
Test multi repo

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#1]
```
name: XNIO-385
components:
  - name: xnio
    org: yersan
    branch: 'bugs/XNIO-385'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: main
    dependencies:
      - name: xnio
        property: version.org.jboss.xnio
  - name: wildfly
    org: wildfly
    branch: master
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
