### ISSUE TITLE
XNIO-385 on JBoss Remoting

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#12]
```
name: XNIO-385
components:
  - name: xnio
    org: yersan
    branch: bugs/XNIO-385
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: yersan
    branch: 5.0.23.Final
    mavenOpts: -DallTests
    java-version: 8
    dependencies:
      - name: xnio
        property: xnio.version
```
