### ISSUE TITLE
Only WildFly

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#15]
```
name: WILDFLY
components:
  - name: wildfly-core
     org: wildfly
     branch: main
     mavenOpts: -fae -DallTests
  - name: wildfly
     org: wildfly
     branch: master
     mavenOpts: -fae -DallTests
     dependencies:
      - name: wildfly-core
         property: version.org.wildfly.core
```
