### ISSUE TITLE
JBoss Remoting

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#17]
```
name: jboss-remoting
components:
  - name: jboss-remoting
    org: jboss-remoting
    branch: '5.0.23.Final'
    mavenOpts: -DskipTests
    dependencies:
      - name: xnio
        property: xnio.version
```
