### ISSUE TITLE
jboss-remoting

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#19]
```
name: jboss-remoting
components:
  - name: jboss-remoting
    org: jboss-remoting
    branch: '5.0.23.Final'
    java-version: 8
```
