### ISSUE TITLE
jboss-remoting XNIO-385_3.7

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#20]
```
name: jboss-remoting
components:
  - name: xnio
    org: yersan
    branch: 'bugs/XNIO-385_3.7'
    java-version: 8
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: jboss-remoting
    branch: '5.0.23.Final'
    java-version: 8
```
