### ISSUE TITLE
XNIO-385 WildFly integration run #2

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#22]
```
name: jboss-remoting
components:
  - name: xnio
    org: yersan
    branch: 'bugs/XNIO-385_3.7'
    java-version: 8
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: main
    java-version: 8
    mavenOpts: -fae -DallTests
    dependencies:
      - name: xnio
        property: version.org.jboss.xnio
  - name: wildfly
    org: wildfly
    branch: master
    java-version: 8
    mavenOpts: -fae -DallTests
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
