### ISSUE TITLE
XNIO-385-3.8 WildFly integration run #3

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#30]
```
name: XNIO-385
components:
  - name: xnio
    org: yersan
    branch: 'XNIO-385-3.8'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: main
    mavenOpts: -fae -DallTests
    dependencies:
      - name: xnio
        property: version.org.jboss.xnio
  - name: wildfly
    org: wildfly
    branch: main
    mavenOpts: -fae -DallTests
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
