### ISSUE TITLE
XNIO-385-3.8 (simple) #1.5

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#55]
```
name: XNIO-385
  - name: wildfly-core
    org: yersan
    branch: WFCORE-5386
    mavenOpts: -fae -DallTests
  - name: wildfly
    org: wildfly
    branch: main
    mavenOpts: -fae -DallTests
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
