### ISSUE TITLE
XNIO-385-3.8 (simple) #2.2

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#57]
```
name: XNIO-385
components:
  - name: wildfly-core
    org: yersan
    branch: WFCORE-5386
    mavenOpts: -fae -DskipTests -Dxnio-385
  - name: wildfly
    org: yersan
    branch: WFCORE-5386
    mavenOpts: -fae -DallTests -Dxnio-385
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
