### ISSUE TITLE
XNIO-385-3.8 (simple) #2.5

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#60]
```
name: XNIO-385
components:
  - name: wildfly-core
    org: yersan
    branch: WFCORE-5386
    mavenOpts: -fae -DskipTests -Dversion.org.jboss.xnio=3.8.11.Final-XNIO-385 -Pstaged-releases
  - name: wildfly
    org: wildfly
    branch: main
    mavenOpts: -fae -DallTests
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
