### ISSUE TITLE
XNIO-385-3.8.11 #3

### ISSUE THREAD

**Issue by yersan** [yersan/multi-repo-ci#63]
```
name: XNIO-385
components:
  - name: wildfly-core
    org: yersan
    branch: WFCORE-5922-revert
    mavenOpts: -fae -DallTests -Dversion.org.jboss.xnio=3.8.11.Final-XNIO-385 -Pstaged-releases
  - name: wildfly
    org: wildfly
    branch: main
    mavenOpts: -fae -DallTests -Pstaged-releases
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
